version: '3'

services:
   database:
      container_name: mysql
      image: mysql:latest
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
         MYSQL_DATABASE: ${MYSQL_DATABASE}
         MYSQL_USER: ${MYSQL_USER}
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
         - 3306:3306
      expose:
         - 3306
      volumes:
         - template_data:/var/lib/mysql
   phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      links:
         - database
      ports:
         - 80:80
      environment:
         - PMA_ARBITRARY=1

volumes:
   template_data:
