version: '3'

services:
   database:
      image: mongo:latest
      container_name: template_database
      restart: always
      ports:
         - 27017:27017
      expose:
         - 27017
      volumes:
         - template_data:/data/db

volumes:
   template_data:
